#%RAML 1.0
title: a-country-weather-system-api
version: v1
mediaType: application/json

types:
  Country: !include datatypes/Country.raml
  Weather: !include datatypes/Weather.raml
  Error: !include datatypes/Error.raml

traits:
  QueryParameter:
    queryParameters:
      city:
        displayName: Capital
        description: Capital of the country
        type: string
        required: true
      metrics:
        displayName: Metrics
        description: Measurement units (metric for Celsius, imperial for Fahrenheit)
        type: string
        required: false
  ErrorResponse:
    responses:
      400:
        body:
          type: Error
          example: !include examples/errors/400.json
      404:
        body:
          type: Error
          example: !include examples/errors/404.json
      405:
        body:
          type: Error
          example: !include examples/errors/405.json
      406:
        body:
          type: Error
          example: !include examples/errors/406.json            
      415:
        body:
          type: Error
          example: !include examples/errors/415.json
      500:
        body:
          type: Error
          example: !include examples/errors/500.json
      501:
        body:
          type: Error
          example: !include examples/errors/501.json            
 
/country:
  get:
    description: Get information about countries
    is: [ErrorResponse]
    responses:
      200:
        body:
          application/json:
            type: Country[]
            example: !include examples/country-example.json
/weather:
  get:
    description: Get weather based on country
    is: [QueryParameter, ErrorResponse]
    responses:
      200:
        body:
          application/json:
            type: Weather
            example: !include examples/weather-example.json